sonar.projectKey=Notes-Project
sonar.projectName=Notes-Project
sonar.sources=frontend/src,backend
sonar.tests=frontend/src,backend/tests
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/node_modules/**,**/coverage/**,**/.nyc_output/**,backend/tests/**,frontend/src/**/*.test.js,frontend/src/**/*.test.jsx
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.sourceEncoding=UTF-8